### PR TITLE
Fixes bug when camera answers with one line only

### PR DESCRIPTION
**Pull request by lattice0**
My camera answered:

```
SETUP rtsp://192.168.1.164:554/11/0 RTSP/1.0
Transport: 
User-Agent: Python Rtsp Client 1.0
CSeq: 2
```

and it broke the code in the line

`(msg, tmp) = tmp.split(HEADER_END_STR, 1)`

it seems it was expecting 2 line responses but my camera, as you see, responded with one line only. I fixed it by returning an empty second element if the camera's answer is one line.

I'm not familiar with RTSP, don't know if I did the right thing, but it worked.

### CODE REVIEW

**Comment by killian441** [comment]
The RTSP standard requires headers to end with a two carriage return line feeds. If your camera doesn't return two then it isn't compliant with the standard, and certainly in this case we shouldn't fail like you are seeing. It is possible that your camera is replying with a '\n\r\n\r' instead of '\r\n\r\n'. If this is the case then we should fix the code, if you can show the raw output (something like `print(repr(response))` would be good) we can see what it is responding.

**Comment by lattice0** [comment]
This is the output:

`'RTSP/1.0 406 Not Acceptable\r\nServer: HiIpcam/V100R003 VodServer/1.0.0\r\nCseq: 2\r\nRequire: Transport settings of rtp/udp;port=nnnn. \r\n'`

so I think the camera isn't really compliant. However it's vstarcam, one of aliexpress top sellers. Shouldn't the correction be worth?

**Comment by killian441** [comment]
The camera looks like it is probably is compliant. There is one case where the server responds by closing the connection rather than with two carriage returns, which is what I'm guessing is happening here. The code does not deal with this case and it should, but I'm not sure your commit is the right way to deal with it. Let me take some time to think about it.

**Comment by killian441** [comment]
In the case where the server responds with a single CRLF and then closes the connection, this is an error state. A response of 406 by your camera would cause the code to fail even with your fix. If you can get this behavior to repeat (single CRLF) with a response of 100, 200 or 3xx then your camera is not compliant and we can reopen this issue. But for now I will add an exception to the code you identified so that the code provides a better explanation of the failure. But it will be up to the end users code to deal with this exception.

**Comment by lattice0** [comment]
That's odd, because my commit worked when I tested. the error did not occur anymore

**Comment by killian441** [comment]
I meant that a 406 code is an error response and so the client will just
send a teardown message and close the connection. So I think raising an
exception here is fine, but like I said if this happens with a 200 or 300
response then its a different story.

**Pull request closed without merging**
